version: 2

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH} 
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

.linux_job: &linuxjob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
    - run:
        name: Curl
        command: .circleci/git_no_checkin_in_last_day.sh || (cd curl && docker build -t oqs-curl .)

.mac_job: &macjob
    macos:
       xcode: "11.3.0"
    steps:
        - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
        - run:
            name: Install dependencies
            command: |
              .circleci/git_no_checkin_in_last_day.sh || (
              brew update &&
              brew unlink python@2 &&
              brew install docker
              )
        - run:
            name: Curl
            command: .circleci/git_no_checkin_in_last_day.sh || (cd curl && docker build -t oqs-curl .)

jobs:
  debian-buster-amd64:
    <<: *linuxjob
    environment:
      IMAGE: openquantumsafe/ci-debian-buster-amd64:latest
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
  ubuntu-bionic-x86_64:
    <<: *linuxjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
  ubuntu-bionic-x86_64-noconn:
    <<: *linuxjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
      SKIP_TESTS: connection
  ubuntu-bionic-x86_64-shared:
    <<: *linuxjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
      LIBTYPE: shared
  ubuntu-bionic-x86_64-shared-noconn:
    <<: *linuxjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
      LIBTYPE: shared
      SKIP_TESTS: connection
  macOS-shared-noconn:
    <<: *macjob
    environment:
      LIBTYPE: shared
      SKIP_TESTS: connection
  macOS-shared:
    <<: *macjob
    environment:
      LIBTYPE: shared
  macOS-static:
    <<: *macjob
    environment:
      LIBTYPE: no-shared
      SKIP_TESTS: connection

workflows:
  version: 2
  build:
    jobs:
      - macOS-shared-noconn    
      - ubuntu-bionic-x86_64-shared-noconn
      - ubuntu-bionic-x86_64-noconn
  nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - macOS-shared    
      - debian-buster-amd64
      - macOS-static    
      - ubuntu-bionic-x86_64
      - ubuntu-bionic-x86_64-shared

