FROM ubuntu:19.10

RUN apt-get update -qq && apt-get upgrade -y && apt-get dist-upgrade -y 

COPY opt /opt

COPY startup-appliance.sh /opt/haproxy/startup.sh
COPY haproxy-appliance.cfg /opt/haproxy/haproxy.cfg
WORKDIR /opt/haproxy

CMD ["/opt/haproxy/startup.sh"]
