From alpine

MAINTAINER MIB (mib@zurich.ibm.com)

ENV DEBIAN_FRONTEND noninteractive

RUN apk update && apk upgrade && apk add lighttpd && rm -rf /var/cache/apk/*

ADD opt /opt
ADD startup.sh /opt/haproxy/startup.sh
ADD haproxy.cfg /opt/haproxy/haproxy.cfg

CMD ["/bin/sh"]
