From alpine

MAINTAINER MIB (mib@zurich.ibm.com)

ENV DEBIAN_FRONTEND noninteractive

ADD opt /opt
ADD startup-mini.sh /opt/haproxy/startup.sh
ADD haproxy.cfg /opt/haproxy/haproxy.cfg

CMD ["/bin/sh"]
