From haproxy-alpine

MAINTAINER MIB (mib@zurich.ibm.com)

ENV DEBIAN_FRONTEND noninteractive

USER oqs
ADD CA.crt /opt/haproxy/CA.crt

WORKDIR /opt/haproxy
#ENV OQSINTERNALS 1
#ENV OQSWARNINGDISABLE 1

ENTRYPOINT ["/opt/haproxy/client/startup.sh"]
