From alpine

MAINTAINER MIB (mib@zurich.ibm.com)

ENV DEBIAN_FRONTEND noninteractive

RUN apk update && apk upgrade 

ADD opt /opt
ADD haproxy-appliance.cfg /opt/haproxy/haproxy.cfg
ADD CA.crt /opt/haproxy/CA.crt

WORKDIR /opt/haproxy
ENV OQSINTERNALS 1
ENV OQSWARNINGDISABLE 1

CMD ["/opt/oqssa/sbin/haproxy", "-f", "/opt/haproxy/haproxy.cfg"]
